### ISSUE TITLE
[Enhancement] Would be great to have a finish message

### ISSUE THREAD

**Issue by pinkfloydFR** [pmongloid/flipdown-timer-card#13]
Hi, first of all thanks for this code ! Work perfectly on my HA !

It would be nice to have so message, color, or something displaying when timer finish in place of display the reset/default/idle time.

Some idea :  

- Displaying " ** : ** : ** " in blinking or another color mode ? 
- Displaying FINISH in place of the time ? 
- Displaying FI:NI:SH in place of the time ? 

Thanks a lot again !

**Comment by BebeMischa** [comment]
This is an example of an automation, that generates a notification after a timer finishes. You can play with the code and let anything happen, you like. Blink a light, play sound, whatever...

```
alias: Timer stop
description: ''
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kookwekker1
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kookwekker2
condition: []
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.vlc_telnet
    data:
      media_content_id: http://xxx.xxx.xxx.xx:8123/local/ns-ding-dong.mp3
      media_content_type: music
  - delay:
      hours: 0
      minutes: 0
      seconds: 4
      milliseconds: 0
  - service: notify.vlctelnetha
    data:
      message: Ik zou je roepen, als dat prutje in de pan klaar is. Dat is dus nu.
mode: single
```

I just like, that after the timer finishes, it goes ready to be used again ;-)
