### ISSUE TITLE
Border when embedded since 2022.11.0

### ISSUE THREAD

**Issue by julienlarivee** [pmongloid/flipdown-timer-card#28]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
V0.4

**Last working release (if known):**
Worked before installing HA 2022.11.0

**Browser and Operating System:**
Chrome

**Description of problem:**
When the card is embedded in an entities card, there is a border around the flipdown timer card.
Before HA 2022.11.0, there was no border.

![image](https://user-images.githubusercontent.com/55027006/205512933-a1f4250f-b1b5-49a2-8a33-29e94ad6f50b.png)
```
type: entities
entities:
  - entity: climate.air_climatise
    group: true
    type: custom:mini-climate
  - entity: timer.air_climatise
    type: custom:flipdown-timer-card
```

If we look at the same entities, but with native HA cards, there is still no border in 2022.11.0
![image](https://user-images.githubusercontent.com/55027006/205513099-be0815e7-d454-4ff8-b244-2b837d7c7845.png)
```
type: entities
entities:
  - entity: climate.air_climatise
  - entity: timer.air_climatise
```

Also, the time picker card had the same issue, but they fixed it. Here is the link to it if it can help:
https://github.com/GeorgeSG/lovelace-time-picker-card/issues/43
