### ISSUE TITLE
No timer entity

### ISSUE THREAD

**Issue by PrzemekSkw** [pmongloid/flipdown-timer-card#4]
Hi, I try to use that card but I don't have any time entity.
Regards.

**Comment by BebeMischa** [comment]
You must make them yourself.

In configuration.yaml put something like this:

```
# Timers
timer:
  timer:
  eggs:
  pasta:
  potatoes:
  slowbakedmeat:
```
