### ISSUE TITLE
use as clock?

### ISSUE THREAD

**Issue by sebatze** [pmongloid/flipdown-timer-card#8]
Is it possible to just show the current time with this?

**Comment by hassuser** [comment]
Is it possible to just use it as a clock?

**Comment by kelvincabaldo07** [comment]
Hi, may we request for it to be used with the current time as well? it would be really appreciated. thanks a lot!

**Comment by AndreiGr** [comment]
Hi there guys,

After a bit of templating it seems like this template sensor should do the trick:
_states.sensor.test_clock.last_changed_ is the last changed attribute of the sensor you're defining, so make sure you modify it with your actual name.
```
- sensor:
    - name: "Test clock"
      state: active
      attributes:
        remaining: >
          {% set duration = (as_timestamp(now())-as_timestamp(states.sensor.test_clock.last_changed))+as_timestamp(now())-as_timestamp(today_at("00:00"))+59 %}
          {{duration//3600}}:{{(duration%3600)//60}}:{{((duration%3600)%60)}}
```

If you have any questions/suggestions, feel free to tell me 😁
